# Generated by Django 5.2 on 2025-05-13 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='end_date',
            field=models.DateTimeField(verbose_name='종료일'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='완료 여부'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='start_date',
            field=models.DateTimeField(verbose_name='시작일'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=50, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
    ]
