# Generated by Django 5.2 on 2025-04-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('url', models.URLField(verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
        ),
    ]

    #makemigrations => migration.py 파일 생성
    #실제 DB에 영향 없음 => 실제 DB에 넣기 위한 정의를 하는 파일을 생성
    #migrate => migrations/ 폴더 안에 있는 migration 파일들을 실제 DB에 적용을 한다.

    #makemigrations => 깃의 Commit => github에 적용 안됨, 커밋 기록 => DB적용 안됨. 적용할 파일 생성
    #migrate => 깃의 push => github에 적용됨. 로컬에 있는 커밋 기록 => DB 적용됨. migrations 파일들 가지고 적용

